### ISSUE TITLE
UDP Not Working

### ISSUE THREAD

**Issue by amurikurthy** [remoteit/multiport#1]
Hello, I'm trying to get TCP & UDP Working on RDP (Port 3389), The software works great with TCP, but I'm having a lot of trouble trying to get UDP to work as well. Any suggestions? Any other documentation? I'm trying to get both working to get a better RDP experience. I have tried the following command and it only works for TCP. 

RUN COMMAND:
muxer.x86_64-win.exe -v -v -t localhost:33005 T3389 U3389

**Comment by lowerpower** [comment]
I think there is a bug in large datagrams for UDP will try to fix

**Comment by lowerpower** [comment]
Cleaned up lots of stuff, I think it will work now
